# Generated by Django 5.1.1 on 2024-10-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_user_alter_lessonlog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonlog',
            old_name='duration',
            new_name='unit',
        ),
    ]
